### PR TITLE
Add husky and csharpier for auto format on commit

### PR DESCRIPTION
**Pull request by betofloresbaca**
To have consistency on code  and to avoid adding complexity to future pull requests I added `csharpier` as a formatter to process *.cs files prior to commit.

* [csharpier](https://csharpier.com/) is n opinionated and fast C# formatting tool with extensions for most popular C# IDEs. Note that the IDE extension is not needed to format on pre-commit.
* [husky](https://typicode.github.io/husky/) is a node tool to easily create git hooks.

I think `csharpier` is a good formatting tool but if another is preferred over this one it is easy to be replaced.

### CODE REVIEW

**Comment by betofloresbaca** [comment]
If you like this developing feature I can help you adding this to the other SharpEngine projects.

**Comment by AlexisHuvier** [comment]
After some research, I found a dotnet version of Husky (https://alirezanet.github.io/Husky.Net/)
Maybe it's a good alternative without node ?

**Comment by AlexisHuvier** [comment]
I try it in Editor repo : https://github.com/SharpEngine/SharpEngine.Editor
I don't know if it really works but you can see it

**Comment by betofloresbaca** [comment]
I am checking the husky.NET you added in `SharEngine.Editor`

**Comment by betofloresbaca** [comment]
@AlexisHuvier I also prefer adding this development functionality as dotnet tools instead of node tools. Closed in favor of https://github.com/SharpEngine/SharpEngine.Core/pull/4

**Pull request closed without merging**
